### ISSUE TITLE
Undetermined naming

### ISSUE THREAD

**Issue by scoobshub** [neothematrix/hdtorrentsit-cp-provider#3]
Ciao neothematrix, sto usando il tuo searcher e devo dire che è fantastico. Grazie mille! Tuttavia ho un problema, con le release che hanno titoli localizzati in italiano sembra avere problemi di riconoscimento. Un esempio:

[core.media.movie.searcher] Wrong: Animali.Fantastici.E.Dove.Trovarli.2016.ITA.ENG.1080p.BluRay.x264-BLUWORLD.mkv, undetermined naming. Looking for 'Fantastic Beasts and Where to Find Them (2016)'

[core.media.movie.searcher] Wrong: Animali Fantastici E Dove Trovarli (2016) 1080p AC3 ITA DTS AC3 ENG.mkv, undetermined naming. Looking for 'Fantastic Beasts and Where to Find Them (2016)'

Sbaglio qualcosa io oppure c'è qualche problema? Grazie mille!

**Comment by neothematrix** [comment]
ciao,
purtroppo CouchPotato non è il massimo nella gestione dei titoli non in inglese, prova questa modifica:
Aggiungi "languages = it" nella sezione "[core]" del file settings.conf di CouchPotato e riavvialo, questo dovrebbe far si che ti appaia tra i possibili titoli dei film anche quello italiano. Eventualmente puoi anche provare, dopo questa modifica, a scegliere manualmente il titolo del film cliccando sul film e sul menu a tendina che dovrebbe apparirti di fianco al titolo.
